[state]
path = "/Users/darkawower/.config/wallboy/state.json"

[providers.wallhaven]
auth = "${WALLHAVEN}"

[providers.unsplash]
auth = "${UNSPLASH_ACCESS_KEY}"

[providers.local]
recursive = true

[theme]
mode = "auto"

[light]
dirs = ["/Users/darkawower/Pictures/wallpappers/light"]
upload-dir = "/Users/darkawower/Pictures/wallpappers/light"
queries = ["light minimalist illustration", "light minimal line art", "light digital art", "white art"]

[dark]
dirs = ["/Users/darkawower/Pictures/wallpappers/dark"]
upload-dir = "/Users/darkawower/Pictures/wallpappers/dark"
queries = ["night city art", "minimalist illustration", "cyberpunk", "neon", "minimal line art", "digital art", "universe", "epic anime", "arcane"]