keymap:
  - name: Common Super shortcuts
    application:
      not: [Emacs, emacs, "app.zen_browser.zen", zen, org.gnu.Emacs, zen-browser, "org.wezfurlong.wezterm", "com.mitchellh.ghostty"]
    exact_match: true
    remap:
      Super-c: C-c
      Super-v: C-v
      Super-x: C-x
      Super-z: C-z
      Super-a: C-a
      Super-f: C-f
      Super-l: C-l
      Super-t: C-t
      Super-w: C-w
      Super-r: C-r
      Super-s: C-s
      Super-n: C-n
      Super-q: C-q

  - name: Terminals commands
    application:
      only: [alacritty, kitty, wezterm, "org.wezfurlong.wezterm", app.kde.konsole, konsole, "com.mitchellh.ghostty"]
    remap:
      Super-v: C-Shift-v
      Super-c: C-Shift-c
      Super-z: C-Shift-z
      
  - name: Delete
    application:
      not: [Emacs, emacs]
    remap:
      Alt-Backspace: C-u
      Super-Backspace: C-Backspace

  - name: GUI shortcuts
    application:
      only: [brave-browser, org.mozilla.firefox, "app.zen_browser.zen", zen, org.telegram.desktop]
    remap:
      C-j: C-Tab
      C-k: C-Shift-Tab
      Alt-Left: Home
      Alt-Right: End
      Super-a: C-a
      Super-c: C-c
      Super-v: C-v
      Super-z: C-z


  - name: Browser shortcuts
    application:
      only: [brave-browser, org.mozilla.firefox, "app.zen_browser.zen", zen]
    remap:
      Super-f: C-f
      Super-1: C-1
      Super-2: C-2
      Super-3: C-3
      Super-4: C-4
      Super-5: C-5
      Super-6: C-6
      Super-7: C-7
      Super-8: C-8
      Super-9: C-9
      Super-z: C-z


  - name: Ctrl+Meta arrows
    remap:
      C-Super-h: Left
      C-Super-j: Down
      C-Super-k: Up
      C-Super-l: Right

  - name: Fn tabs
    remap:
      Fn-j: C-Tab
      Fn-k: C-S-Tab

  - name: Emacs
    application:
      only: emacs
    remap:
      S-k: S-k
      Super-c: Super-c
      Super-v: Super-v
      # Super-Dot: Super-Dot
