keymap:
  - name: Super shortcuts
    application:
      not: [Emacs, emacs, "app.zen_browser.zen", zen, org.gnu.Emacs, zen-browser]
    remap:
      Super-c: C-c
      Super-v: C-v
      Super-x: C-x
      Super-z: C-z
      Super-a: C-a
      Super-f: C-f
      Super-l: C-l
      Super-t: C-t
      Super-w: C-w
      Super-r: C-r
      Super-s: C-s
      Super-n: C-n
      Super-q: C-q

  - name: Next/prev tab
    application:
      only: [zen, app.zen_browser.zen, org.telegram.desktop]
    remap:
      C-j: C-Tab
      C-k: C-Shift-Tab
      Super-c: C-c
      Super-v: C-v

  - name: Ctrl+Meta arrows
    remap:
      C-Super-h: Left
      C-Super-j: Down
      C-Super-k: Up
      C-Super-l: Right

  - name: Fn tabs
    remap:
      Fn-j: C-Tab
      Fn-k: C-S-Tab

  - name: Disable Shift-k remap in Emacs
    application:
      only: emacs
    remap:
      S-k: S-k
      Super-c: Super-c
      Super-v: Super-v
